DROP TABLE IF EXISTS genres;
CREATE TABLE genres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE CHECK (birthday <= CURRENT_DATE)
);


create table friends (
    user_id bigint references users(id) not null,
    friend_id bigint references users(id) not null ,
    primary key (user_id, friend_id)
);
