DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS mpa;

CREATE TABLE genres (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE CHECK (birthday <= CURRENT_DATE)
);

create table friends (
    user_id bigint references users(id) ON DELETE CASCADE not null ,
    friend_id bigint references users(id) ON DELETE CASCADE not null ,
    primary key (user_id, friend_id)
);

CREATE TABLE mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

CREATE TABLE films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE CHECK (release_date >= DATE '1895-12-28'),
    duration INTEGER CHECK (duration > 0),
    mpa_id INTEGER REFERENCES mpa(id) ON DELETE SET NULL
);

CREATE TABLE film_genres (
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);


CREATE TABLE likes (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    film_id BIGINT REFERENCES films(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);


